export const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export const USER_NAME = "userName";
export const PENDING = "pending";
export const FINISHED = "finished";
export const DEL = "del";
export const CHECK = "check";
export const BACK = "back";
export const BTN = "btn";
export const COORDS = "coords";
